// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017-2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
const awsmobile = {
    'aws_app_analytics': 'enable',
    'aws_cognito_identity_pool_id': 'us-east-1:8cb990cd-819f-419b-a50c-91b304f1ccb0',
    'aws_cognito_region': 'us-east-1',
    'aws_mobile_analytics_app_id': '439bc931ceee4253b62eada008d77fc7',
    'aws_mobile_analytics_app_region': 'us-east-1',
    'aws_project_id': '7a729110-1b3b-4b3a-82b7-6498d26d3de4',
    'aws_project_name': 'blindbus',
    'aws_project_region': 'us-east-1',
    'aws_resource_name_prefix': 'blindbus-mobilehub-97315362',
}

export default awsmobile;
